server.port=${PORT:5000}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/auralens}

# Custom security configuration settings
app.jwt.secret=${JWT_SECRET:auralens_jwt_secret_key_12345_super_long_secret_key_required_by_jjwt_library}
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:adminpassword}

# Multipart File Upload Properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
